---
abstract: '絵文字を一回かいたら、3キャリで表示できるようにするフィルタ'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Pictogram-MobileJp
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::MobileAgent: 0
  perl: 5.8.0
version: 0.01
